server:
  port: 9002

spring:
  application:
    name: consumer-service

  autoconfigure:
    exclude: org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration

  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        metadata:
          preserved.heart.beat.interval: 1000
          preserved.heart.beat.timeout: 3000
          preserved.heart.delete.timeout: 3000
    consul:
      discovery:
        hostname: localhost
        port: 8500
        heartbeat:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/